// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PermitTorch.Api.Data;

#nullable disable

namespace PermitTorch.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260928145324_AddPermitRecordLink")]
    partial class AddPermitRecordLink
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PermitTorch.Api.Data.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firebase_uid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_app_users");

                    b.HasIndex("FirebaseUid")
                        .IsUnique()
                        .HasDatabaseName("ix_app_users_firebase_uid");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_app_users_organization_id");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.EmailPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer")
                        .HasColumnName("frequency");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_email_preferences");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_email_preferences_user_id");

                    b.ToTable("email_preferences", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.FireOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<bool>("CategoryOverridden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("category_overridden");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("FirstDetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_detected_at");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("LeadScore")
                        .HasColumnType("integer")
                        .HasColumnName("lead_score");

                    b.Property<Guid>("PermitId")
                        .HasColumnType("uuid")
                        .HasColumnName("permit_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.HasKey("Id")
                        .HasName("pk_fire_opportunities");

                    b.HasIndex("PermitId")
                        .IsUnique()
                        .HasDatabaseName("ix_fire_opportunities_permit_id");

                    b.ToTable("fire_opportunities", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.LeadSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("FireOpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("fire_opportunity_id");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("signal_type");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_lead_signals");

                    b.HasIndex("FireOpportunityId")
                        .HasDatabaseName("ix_lead_signals_fire_opportunity_id");

                    b.ToTable("lead_signals", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Market", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_markets");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_markets_slug");

                    b.ToTable("markets", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organizations");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Permit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ApplicantName")
                        .HasColumnType("text")
                        .HasColumnName("applicant_name");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text")
                        .HasColumnName("business_name");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("ContractorName")
                        .HasColumnType("text")
                        .HasColumnName("contractor_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("numeric")
                        .HasColumnName("estimated_value");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<DateTime?>("FiledDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("filed_date");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("fingerprint");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTime?>("InspectionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("inspection_date");

                    b.Property<DateTime?>("IssuedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_date");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text")
                        .HasColumnName("owner_name");

                    b.Property<string>("PermitNumber")
                        .HasColumnType("text")
                        .HasColumnName("permit_number");

                    b.Property<string>("PermitType")
                        .HasColumnType("text")
                        .HasColumnName("permit_type");

                    b.Property<string>("PropertyType")
                        .HasColumnType("text")
                        .HasColumnName("property_type");

                    b.Property<string>("RawStatus")
                        .HasColumnType("text")
                        .HasColumnName("raw_status");

                    b.Property<string>("RecordType")
                        .HasColumnType("text")
                        .HasColumnName("record_type");

                    b.Property<string>("RecordUrl")
                        .HasColumnType("text")
                        .HasColumnName("record_url");

                    b.Property<int?>("RecordUrlKind")
                        .HasColumnType("integer")
                        .HasColumnName("record_url_kind");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<int?>("SquareFootage")
                        .HasColumnType("integer")
                        .HasColumnName("square_footage");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkType")
                        .HasColumnType("text")
                        .HasColumnName("work_type");

                    b.Property<string>("Zip")
                        .HasColumnType("text")
                        .HasColumnName("zip");

                    b.HasKey("Id")
                        .HasName("pk_permits");

                    b.HasIndex("Fingerprint")
                        .HasDatabaseName("ix_permits_fingerprint");

                    b.HasIndex("SourceId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_permits_source_id_external_id");

                    b.ToTable("permits", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.PermitParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PermitId")
                        .HasColumnType("uuid")
                        .HasColumnName("permit_id");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_permit_participants");

                    b.HasIndex("PermitId")
                        .HasDatabaseName("ix_permit_participants_permit_id");

                    b.ToTable("permit_participants", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.SampleLeadRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime?>("LastSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_sent_at");

                    b.Property<string>("MarketSlug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("market_slug");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sample_lead_requests");

                    b.HasIndex("Email", "MarketSlug")
                        .IsUnique()
                        .HasDatabaseName("ix_sample_lead_requests_email_market_slug");

                    b.ToTable("sample_lead_requests", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.SavedLead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FireOpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("fire_opportunity_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_saved_leads");

                    b.HasIndex("FireOpportunityId")
                        .HasDatabaseName("ix_saved_leads_fire_opportunity_id");

                    b.HasIndex("UserId", "FireOpportunityId")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_leads_user_id_fire_opportunity_id");

                    b.ToTable("saved_leads", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.ScraperRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApifyRunId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apify_run_id");

                    b.Property<int>("Classified")
                        .HasColumnType("integer")
                        .HasColumnName("classified");

                    b.Property<string>("CoverageReportJson")
                        .HasColumnType("text")
                        .HasColumnName("coverage_report_json");

                    b.Property<int>("DuplicatesSkipped")
                        .HasColumnType("integer")
                        .HasColumnName("duplicates_skipped");

                    b.Property<double>("DurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("duration_seconds");

                    b.Property<int>("Failures")
                        .HasColumnType("integer")
                        .HasColumnName("failures");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("RecordsImported")
                        .HasColumnType("integer")
                        .HasColumnName("records_imported");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_scraper_runs");

                    b.HasIndex("ApifyRunId")
                        .IsUnique()
                        .HasDatabaseName("ix_scraper_runs_apify_run_id");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_scraper_runs_source_id");

                    b.ToTable("scraper_runs", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<int>("HealthStatus")
                        .HasColumnType("integer")
                        .HasColumnName("health_status");

                    b.Property<string>("Jurisdiction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jurisdiction");

                    b.Property<DateTime?>("LastRecordSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_record_seen_at");

                    b.Property<DateTime?>("LastSuccessfulRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_run_at");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PortalType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("portal_type");

                    b.Property<int>("RecordsLastRun")
                        .HasColumnType("integer")
                        .HasColumnName("records_last_run");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_url");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_sources");

                    b.HasIndex("Jurisdiction")
                        .IsUnique()
                        .HasDatabaseName("ix_sources_jurisdiction");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("ix_sources_market_id");

                    b.ToTable("sources", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("Plan")
                        .HasColumnType("integer")
                        .HasColumnName("plan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("StripeSubscriptionId")
                        .HasColumnType("text")
                        .HasColumnName("stripe_subscription_id");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_ends_at");

                    b.HasKey("Id")
                        .HasName("pk_subscriptions");

                    b.HasIndex("OrganizationId")
                        .IsUnique()
                        .HasDatabaseName("ix_subscriptions_organization_id");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.SubscriptionMarket", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<Guid>("MarketId")
                        .HasColumnType("uuid")
                        .HasColumnName("market_id");

                    b.HasKey("SubscriptionId", "MarketId")
                        .HasName("pk_subscription_markets");

                    b.HasIndex("MarketId")
                        .HasDatabaseName("ix_subscription_markets_market_id");

                    b.ToTable("subscription_markets", (string)null);
                });

            modelBuilder.Entity("PermitTorch.Api.Data.AppUser", b =>
                {
                    b.HasOne("PermitTorch.Api.Data.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_app_users_organizations_organization_id");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.EmailPreference", b =>
                {
                    b.HasOne("PermitTorch.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_email_preferences_app_users_user_id");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.FireOpportunity", b =>
                {
                    b.HasOne("PermitTorch.Api.Data.Permit", "Permit")
                        .WithOne("Opportunity")
                        .HasForeignKey("PermitTorch.Api.Data.FireOpportunity", "PermitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fire_opportunities_permits_permit_id");

                    b.Navigation("Permit");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.LeadSignal", b =>
                {
                    b.HasOne("PermitTorch.Api.Data.FireOpportunity", null)
                        .WithMany("Signals")
                        .HasForeignKey("FireOpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lead_signals_fire_opportunities_fire_opportunity_id");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Permit", b =>
                {
                    b.HasOne("PermitTorch.Api.Data.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permits_sources_source_id");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.PermitParticipant", b =>
                {
                    b.HasOne("PermitTorch.Api.Data.Permit", null)
                        .WithMany("Participants")
                        .HasForeignKey("PermitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_permit_participants_permits_permit_id");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.SavedLead", b =>
                {
                    b.HasOne("PermitTorch.Api.Data.FireOpportunity", null)
                        .WithMany()
                        .HasForeignKey("FireOpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_leads_fire_opportunities_fire_opportunity_id");

                    b.HasOne("PermitTorch.Api.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_leads_app_users_user_id");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.ScraperRun", b =>
                {
                    b.HasOne("PermitTorch.Api.Data.Source", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .HasConstraintName("fk_scraper_runs_sources_source_id");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Source", b =>
                {
                    b.HasOne("PermitTorch.Api.Data.Market", "Market")
                        .WithMany("Sources")
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sources_markets_market_id");

                    b.Navigation("Market");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Subscription", b =>
                {
                    b.HasOne("PermitTorch.Api.Data.Organization", null)
                        .WithOne("Subscription")
                        .HasForeignKey("PermitTorch.Api.Data.Subscription", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscriptions_organizations_organization_id");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.SubscriptionMarket", b =>
                {
                    b.HasOne("PermitTorch.Api.Data.Market", null)
                        .WithMany()
                        .HasForeignKey("MarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_markets_markets_market_id");

                    b.HasOne("PermitTorch.Api.Data.Subscription", null)
                        .WithMany("Markets")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_subscription_markets_subscriptions_subscription_id");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.FireOpportunity", b =>
                {
                    b.Navigation("Signals");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Market", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Organization", b =>
                {
                    b.Navigation("Subscription");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Permit", b =>
                {
                    b.Navigation("Opportunity");

                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PermitTorch.Api.Data.Subscription", b =>
                {
                    b.Navigation("Markets");
                });
#pragma warning restore 612, 618
        }
    }
}
